feature/BCE-006-sign up/in
boostcampth/boostcamp3_E pull request #16
Opened 2019-01-30 07:30 UTC by Hongbeom

## 개요
로그인 및 회원가입 추가

## 작업사항
1.base package 형식에 맞게 login, signup MVP형식으로 작성
2.Example Activity 오타 수정

resolved #6

2019-01-30 11:38 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/authentication/LoginActivity.java
> -            makeToast("아이디 또는 비밀번호를 입력해 주세요");
String resource로 바꿔주세요

2019-01-30 11:39 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +            showToast("아이디 또는 비밀번호를 입력해 주세요");
String Resrouce로 바꿔주세요

2019-01-30 11:42 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +        presenter.onDetach();
presenter.onDetach는 여러군데에서 호출이 아닌 onPause나 onStop , onDestory 중 한군데로 적합하게 바꿀 수 있을것 같아요

2019-01-30 11:53 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginContractor.java
> +        void startMainActivity();
startSignUpActivity()
startMainActivity()는 메소드 명령이고 MVP상에서 사용하는 의미를 나타내는 것 같아요

startMainActivity()는 onLoginSucces와같이 행동 결과에대한 의미를 부여하는 식으로 전부 바꿔주셔야 할것 같아요

2019-01-30 11:56 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpContractor.java
> +public interface SignUpContractor {
GoogleBluePrint 예제와 같이  MVP형식으로 맞추기로 하였는데 네이밍 규칙이 저희와 다르네요

SignUpContractor -> SignUpContract로 다 같이 통일해야 할것 같아요

2019-01-30 11:56 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpContractor.java
> +
View 도 BaseView가 있으므로 상속해서 사용해주세요

2019-01-30 11:56 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +                showToast("이메일을 입력해 주세요");
StringResource를 사용해주세요

2019-01-30 11:56 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +            showToast("이메일을 입력해 주세요");
StringResource를 사용해주세요

2019-01-30 11:57 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +            showToast("값을 다 입력해주세요");
StringResource를 사용해주세요

2019-01-30 11:57 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        showToast("회원가입 성공"); // 테스트 토스트 - 지워주세요
StringResource를 사용해주세요

2019-01-30 11:58 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginPresenter.java
> +                            view.showToast("에메일과 비밀번호를 확인해 주세요");
StringResource를 사용해주세요

2019-01-30 12:00 UTC, GODueol commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +package com.teame.boostcamp.myapplication.util;
FirebaseAuth를 MVP구조로 만들때 적합한 구조를 Slack을 통하여 전달해드렸습니다. 참고하셔서 수정해보시면 많은 도움이 될 것 같아요

2019-01-30 12:04 UTC, GODueol requested changes
전반적으로 Convention에 대해서 수정을 해주셔야 할 것 같아요

2019-01-30 12:06 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:hint="  Email"
raw값을 StringResource로 바꿔주세요

2019-01-30 12:06 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            name="loginActivity"
loginAcitivity를 사용하지않는데 왜 선언해주신건가요?

2019-01-30 12:07 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_email"
til_email로 바꿔주셔야 할 것 같습니다

2019-01-30 12:08 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            app:layout_constraintHorizontal_bias="0.498"
bias 0.498은 의도하신 값인가요?

2019-01-30 12:08 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            tools:srcCompat="@tools:sample/avatars" />
tools:sample/avatas 는 어떤 역할을 하나요?

2019-01-30 12:09 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:text="로그인 기억하기"
raw값을 StringResource로 바꿔주세요

2019-01-30 12:09 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:text="회원가입"
raw값을 StringResource로 바꿔주세요

2019-01-30 12:09 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:text="로그인"
raw값을 StringResource로 바꿔주세요

2019-01-30 12:10 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_login"
btn_login과 btn_register가 같은 속성을 많이 사용하는데 Style로 묶어주시면 추후에 수정할때 용이할수도 있을것같아요

2019-01-30 12:10 UTC, GODueol commented on app/src/main/res/layout/activity_login.xml
> +        <CheckBox xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:android 속성이 CheckBox에 속해있는데
특별하게 의도된게 아니라면 <layout>루트 에만 선언해주면 될것 같은데 이유가 있나요?

2019-01-30 12:11 UTC, GODueol requested changes
raw value들이 많이보여서 String resource로 변환작업이 필요해보입니다~

2019-01-30 12:18 UTC, GODueol requested changes
다른 review에 남긴 사항들을 참고하여 같이 고쳐주세요
Contractor -> Contract
Contract.View의 method의 네이밍
raw텍스트를 StringResrouce로 변경
빈 메소드 공백(엔터) 제거 등

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +            showToast("아이디 또는 비밀번호를 입력해 주세요");
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginContractor.java
> +        void startMainActivity();
succeedLogIn(), succeedSignUp() 등의 이름으로 변경하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpContractor.java
> +public interface SignUpContractor {
수정완료하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpContractor.java
> +
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +                showToast("이메일을 입력해 주세요");
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +            showToast("이메일을 입력해 주세요");
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +            showToast("값을 다 입력해주세요");
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        showToast("회원가입 성공"); // 테스트 토스트 - 지워주세요
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginPresenter.java
> +                            view.showToast("에메일과 비밀번호를 확인해 주세요");
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +package com.teame.boostcamp.myapplication.util;
자료 참고하여 변경하였습니다. AuthenticationUtil 클래스를 삭제한뒤 presenter에서 auth를 진행하는 방향으로 수정하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:hint="  Email"
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_email"
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            app:layout_constraintHorizontal_bias="0.498"
로고를 위한 이미지뷰인데 마우스로 디자인을 설정하다가 값이 잘못들어간것 같습니다. 수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            tools:srcCompat="@tools:sample/avatars" />
안드로이드 스튜디오에서 이미지뷰를 추가할때 기본 아바타 이미지를 선택하여 추가했었습니다. 삭제했습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:text="로그인 기억하기"
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:text="회원가입"
수정완료 하였습니다!

2019-01-30 16:26 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:text="로그인"
수정완료 하였습니다!

2019-01-30 16:28 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_login"
넵 조언 감사합니다.  버튼 스타일은 내일 한번더 물어보도록 하겠습니다.

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +    }
startSignUpActivity->startActivity로 바꾸시고
context를 첫번째 파라미터로 지정해주신 다음에 activity 시작할때 넘겨야 할 데이터가 있다면 파라미터로 넘겨주시고
startActivity 파라미터로 넘기는 intent는 함수 안에서 선언해주시면 감사하겠습니다.
그리고 startActivity는 context.startActivity(intent)로 바꿔주시기 바랍니다.

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +}
startMainActivity->finishActivity로 바꾸시고 파라미터로 context넘겨준 다음에
context.finish()로 바꿔주시기 바랍니다.

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginPresenter.java
> +                        }
에메일->이메일

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +    public void initView() {
public->private

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        binding.btnEmailcheck.setOnClickListener(v -> {
람다에서 파라미터 v 안쓰실때는 __(언더바 2개) 로 나타내 주시기 바랍니다.
<밑의 람다식에서도 동일>

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        presenter.onDetach();
위와 동일

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +public class AuthenticationUtil {
util->repository

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +
FirebaseAuth를 가지고 있는 Wrapper클래스를 작성해서 signInWithEmailAndPassword등의 함수를 Wrapper클래스 안에서 처리 후 return값 반환

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_email"
tfl->til

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +                android:id="@+id/et_email"
et->tiet

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_password"
tfl->til

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +                android:id="@+id/et_password"
et->tiet

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/imageView"
imageView->iv_(Description)

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_login"
btn->mb

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_register"
btn->mb

2019-01-31 02:08 UTC, ho8278 commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +    private void startSignUpActivity() {
startSignUpActivity->onSignUpButtonClicked()로 바꿔주세요

2019-01-31 03:33 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +        <CheckBox xmlns:android="http://schemas.android.com/apk/res/android"
마우스를 이용하여 설정하다가 값이 이상하게 들어갔습니다. checkbox가 쓸모가 없어져 삭제하는 방향으로 수정하였습니다.

2019-01-31 03:34 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_register"
수정완료했습니다!

2d2621a

2019-01-31 03:34 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_email"
수정완료했습니다!

2d2621a

2019-01-31 03:34 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +                android:id="@+id/et_email"
수정완료했습니다!

2d2621a

2019-01-31 03:34 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/tfl_password"
수정완료했습니다!

2d2621a

2019-01-31 03:34 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +                android:id="@+id/et_password"
수정완료했습니다!

2d2621a

2019-01-31 03:35 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/imageView"
수정완료했습니다!

2d2621a

2019-01-31 03:35 UTC, Hongbeom commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btn_login"
수정완료했습니다!

2d2621a

2019-01-31 03:35 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +    private void startSignUpActivity() {
수정완료 하였습니다!

70be9ce

2019-01-31 03:35 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +
util을 삭제하고 presenter에서 auth를 관리하는 방식으로 변경하였습니다!

2019-01-31 03:36 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/util/AuthenticationUtil.java
> +public class AuthenticationUtil {
util을 삭제하고 presenter에서 auth를 관리하는 방식으로 변경하였습니다!

2019-01-31 03:36 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginPresenter.java
> +                        }
수정하였습니다!

2019-01-31 03:36 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        binding.btnEmailcheck.setOnClickListener(v -> {
f0a7566

2019-01-31 03:37 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +    public void initView() {
수정완료 했습니다!
84d0a33

2019-01-31 03:38 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/signup/SignUpActivity.java
> +        presenter.onDetach();
수정완료했습니다!
f0a7566

2019-01-31 03:38 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +}
수정완료했습니다!
70be9ce

2019-01-31 03:38 UTC, Hongbeom commented on app/src/main/java/com/teame/boostcamp/myapplication/ui/login/LoginActivity.java
> +    }
수정완료했습니다!
70be9ce

2019-01-31 04:49 UTC, GODueol approved these changes

2019-01-31 04:54 UTC, merged